### ISSUE TITLE
Add tutorial notebooks to demonstate the stochasticity of layer 0 and layer 1.

### ISSUE THREAD

**Issue by ssinhaleite** [synsense/sinabs#186]
'- [ ] Explain the stochasticity in layer 0 and layer 1
- [ ] Told the user that their model may output different results if use layer0 and layer1 for on-chip testing

**Comment by bauerfe** [comment]
Could someone please explain what this issue is about? @sheiksadique ?

**Comment by sheiksadique** [comment]
On speck, then architecture of the first 2 layers has asynchronous parallel execution and therefore exhibits some level of stochasticity. The rest of the layers not exhibit such stochasticity. 

I believe the issue is here to make this behaviour clear to the users/developers in case they expect non-stochastic behaviour.
