### ISSUE TITLE
New release v2.0

### ISSUE THREAD

**Issue by sheiksadique** [synsense/sinabs#218]
Here is a checklist of things to be done before the release.

- [x] Check documentation and notebooks are understandable @MinaKh 
- [x] Check integration with Exodus @bauerfe 
- [x] Remove redundant files in documentation 
- [x] Refractor tutorials and unify in the toc-tree for hardware and simulations
- [x] Make it clear in README and docs that a development (`-e`) install will not work with EXODUS
- [x] Sinabs-dynapcnn "empty" requirements release with appropriate version requirement to sinabs

**Comment by bauerfe** [comment]
I just added a point that we should point out clearly that a development install will not work with exodus. Thanks for spotting this @MinaKh

**Comment by bauerfe** [comment]
Ticking off the points about Exodus (everything still works) and about refactoring of unit tests (addressed by #221 )

**Comment by MinaKh** [comment]
broken link:

- [ ]   https://github.com/synsense/sinabs/blob/develop/docs/speck/getting_started/overview.md 

-  mentioned in : https://github.com/synsense/sinabs/tree/develop/docs/speck

**Comment by MinaKh** [comment]
In 
https://github.com/synsense/sinabs/blob/develop/docs/speck/faqs/tips_for_training.md
is mentioned that we need to clip weights to the threshold value, as the async chip is designed to emit only 1 spike per dt etc...this is clear but at the end of page  it is stated:

`You'd better choose "Multi-Spike" instead of "Single-Spike" due to the nature of our hardware as demonstrated in the chapter above.`
Am I missing something. Do we have `Multi-Spike` choice?

**Comment by bauerfe** [comment]
Hi @MinaKh , thanks for spotting these. I think I fixed all the broken links now (on develop). Would you mind double-checking?

I also added better explanation about `MultiSpike` in the section you mention. Is it clearer now?

@sheiksadique : I ticked off the point about removing redundant files in the docs. If I'm correct, this referred to the `README.rst` files that sphinx complains about while making the html, right? It turns out it still needs these files to generate the gallery.

**Comment by MinaKh** [comment]
- [ ] several of embedded images in faq and notebooks folders are broken. @bauerfe can you please check them too? 
- [ ] here https://github.com/synsense/sinabs/blob/develop/docs/speck/overview.md
in Leak operation section there is a missing ToDO: [tutorial on how to use leak feature]

**Comment by MinaKh** [comment]
> Hi @MinaKh , thanks for spotting these. I think I fixed all the broken links now (on develop). Would you mind double-checking?
> 
> I also added better explanation about `MultiSpike` in the section you mention. Is it clearer now?
> 
> @sheiksadique : I ticked off the point about removing redundant files in the docs. If I'm correct, this referred to the `README.rst` files that sphinx complains about while making the html, right? It turns out it still needs these files to generate the gallery.

Thanks @bauerfe sounds good now :)

**Comment by sheiksadique** [comment]
> * [ ]  several of embedded images in faq and notebooks folders are broken. @bauerfe can you please check them too?

This was due to rendering of pages in GitHub and the problem is not see in the rendered sphinx pages. Marking as resolved.

**Comment by bauerfe** [comment]
Moved two of the tasks to new issues (#229 , #230)
