### ISSUE TITLE
When recording states, record v_mem before reset

### ISSUE THREAD

**Issue by biphasic** [synsense/sinabs#26]

**Comment by bauerfe** [comment]
I think the initial motivation for this was to be consistent with sinabs-exodus. 
Recently, exodus has been updated to match the current behavior of sinabs. So from this point of view, this issue could be closed.

On the other hand, one could argue that it is convenient to see v_mem before reset, because then it is immediately clear which neurons were above threshold at any given point. Any opinions?

**Comment by biphasic** [comment]
if the behaviour is consistent then personally I'm happy like that.

**Comment by bauerfe** [comment]
Let's leave it like that for now, then.
